name: Coffee Monitor

on:
  schedule:
    - cron: "0 1 * * *"
    - cron: "0 6 * * *"
    - cron: "0 12 * * *"
    - cron: "0 16 * * *"

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4   # ⭐ 升级

      - name: Set up Python
        uses: actions/setup-python@v5   # ⭐ 升级
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 openpyxl

      - name: Run script
        run: |
          python monitor_all.py

      - name: Commit updated Excel
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add .
          git commit -m "update data" || echo "no changes"
          git push
